steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
    - '-c'
    - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"

- id: 'tf init'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - |
      cd lab_2
      terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - | 
      cd lab_2
      terraform plan
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - | 
      cd lab_2
      terraform apply -auto-approve
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
# [END tf-apply]      