steps:
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - |
      cd lab_4
      terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - | 
      cd lab_4
      terraform plan
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
    - 'TF_VAR_node_count=$_NODE_COUNT'
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.0'
  entrypoint: 'sh'
  args: 
    - '-c'
    - | 
      cd lab_4
      terraform apply -auto-approve
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
    - 'TF_VAR_node_count=$_NODE_COUNT'
# [END tf-apply]      